# get data dictionary: http://www.crsp.org/products/documentation/annual-data-industrial
df<-    data.frame(
      stringsAsFactors = FALSE,
      V1 = c("CHE","RECT","INVT","ACT",
             "LCT","AT","PPEGT","PPENT","DLTT","PSTKL","CEQT",
             "SALE","OIBDP","DP","XINT","TXT","SPI","IB","DVP",
             "IBADJ","DVC","PRCH","PRCL","PRCC","CSHO","DVPSX",
             "AJEX","CSHTR","EMP","CAPXV","IVAEQ","IVAO","INTAN",
             "DLC","TXDITC","RE","ICAPT","MIB","DCPSTK","CSHRT",
             "COGS","XLR","XPR","DD1","XAD","XRD","XRENT",
             "XIDO","MII","TXDI","ITCI","TLCF","EPSPI","CSHPRI",
             "ESUB","PSTKRV","EPSFX","EPSPX","INVVAL","CEQ","NOPI",
             "IDIT","TXFED","TXFO","AM","DO","RECD","ACO",
             "AO","AP","TXP","LCO","PPENC","TXDB","LO","INVRM",
             "INVWIP","INVFG","DCVT","DS","DN","DD","DLTO","DCLO",
             "CSTK","TSTKME","TSTKN","TSTK","PCUV","PCUP",
             "DD2","DD3","DD4","DD5","MRCT","MRC1","REUNR","OB",
             "REA","CSHR","XINTD","TXW","XDP","BAST","BASTR",
             "ESUBC","SPPE","SSTK","SIV","FOPT","DLTIS","FSRCT",
             "IVCH","DLTR","PRSTKC","FUSET","SALE","IB","EPSPX",
             "AT","WCAP","PI","IBC","XIDOC","DPC","TXDC","DV",
             "CAPX","AQC","PSTK","COGS","XSGA","DP","XINT","TXT",
             "XIDO","EPSPI","CSHPRI","EPSFX","EPSFI","PPENT",
             "DLTT","REUNA","SEQ","CAPX","EMP","INTC","DLTP",
             "AUOP","FCA","RECTR","DC","XACC","DCVSUB","PPENB",
             "PPENME","PPENNR","PPENLI","PPENLS","XPP","TXR","CH",
             "IRENT","MRC2","MRC3","MRC4","MRC5","CB","EPSFI",
             "PI","CSHFD","NI","TXS","XDEPL","PSTKR","NI","OIADP",
             "WCAP","WCAPCH","LT","PPEVBB","ACCHG","PPEVR",
             "PPEVO","INVO","PPEVEB","DCVSR","XSGA","NOPIO","CSTKE",
             "XI","IVST","RECCO","ACOX","DPACT","PRCH","PRCL",
             "PRCC","CSHRC","DVPSP","AJP","CSHRP","GDWL","AOX",
             "NP","LCOX","ITCB","PSTKN","CAPS","TXO","SPPIV",
             "PSTKC","CSHRSO","SEQ","FOPO","FSRCO","FUSEO",
             "DVPIBB","DPVIR","DPVIO","DPVIEB","NOPI","MII","TSTKP",
             "CURRTR","CSHRW","RECTA","REAJO","CSTKCV","OPEPS",
             "ADRR","CEQL","WCAPC","IBCOM","MSA","NIECI","LIFR",
             "DM","DVPA","PBNVV","PBPVN","PBNAA","PBARR","PBID",
             "AQI","AQS","PPENO","DPACLI","DPACNR","DPACB",
             "DPACME","DPACLS","DPACC","DPACO","NIADJ","REUNA","FATP",
             "FATN","FATB","FATE","FATL","FATC","FATO","DUDD",
             "TXDFED","TXDFO","TXDS","PIDOM","PIFO","CHECH",
             "SPMIM","SPIIM","FORI","FORRK","SPLTICRM","SPCSRM",
             "SPSTICRM","PBVNO","PBACO","PBPRO","PPLAO","PCUPSO",
             "POAJO","PCPPAO","PBVNU","PPRBC","PBACU","PBPRU",
             "PPC","PPLAU","PCUPSU","PADDML","POAJU","PCPPAU",
             "DLCCH","RECCH","INVCH","APALCH","TXACH","AOLOCH","OANCF",
             "IVSTCH","IVACO","IVNCF","FIAO","FINCF","EXRE",
             "INTPN","TXPD","SCF","DILADJ","SPSDRM","TII","DILAVX",
             "OPREPSX","SICH","CLG","DFS","DCS","PRBA","PPSC",
             "PPIC","PPRPA","PPOPCC","PPRCI","PPROR","CAPR1",
             "TIE","NIIT","NPAT","PLL","RLL","NIM","CAPRT","NCO",
             "ACDO","INTANO","ALDO","ACODO","AODO","DRC",
             "ACOMINC","DCOM","SEQO","AQP","AQA","AQEPS","AQD","GLP",
             "GLA","GLEPS","GLD","GDWLIP","GDWLIA","GDWLIEPS",
             "GDWLID","SETP","SETA","SETEPS","SETD","RCP","RCA",
             "RCEPS","RCD","WDP","WDA","WDEPS","WDD","SPIOP",
             "SPIOA","SPIEPS","SPID","RDIP","MRCTA","DPACRE",
             "XPFRET","SRET","DPRET","GDWLAM","CSHI","DRLT","STKCO",
             "XINTOPT","TXBCOF","RDIPEPS","RDIPD","NRTXT",
             "NRTXTEPS","NRTXTD","DTEP","DTEA","DTEEPS","DTED",
             "XOPTEPS","XOPTD"),
      V2 = c(1L,1L,1L,1L,1L,1L,1L,1L,
             1L,1L,1L,1L,1L,1L,1L,1L,1L,1L,1L,1L,1L,31L,
             31L,31L,1L,32L,1L,31L,1L,1L,1L,1L,1L,1L,1L,
             1L,1L,1L,1L,1L,1L,1L,1L,1L,1L,1L,1L,1L,1L,
             1L,1L,1L,1L,1L,1L,1L,1L,1L,14L,1L,1L,1L,1L,
             1L,1L,1L,1L,1L,1L,1L,1L,1L,1L,1L,1L,1L,1L,1L,
             1L,1L,1L,1L,1L,1L,1L,1L,1L,1L,1L,1L,1L,1L,
             1L,1L,1L,1L,1L,1L,1L,1L,1L,1L,1L,1L,1L,1L,
             1L,1L,1L,1L,1L,1L,1L,1L,1L,1L,2L,2L,2L,2L,
             2L,2L,1L,1L,1L,1L,1L,1L,1L,1L,2L,2L,2L,2L,2L,
             2L,2L,2L,2L,2L,2L,2L,2L,2L,2L,2L,1L,1L,14L,
             1L,1L,1L,1L,1L,1L,1L,1L,1L,1L,1L,1L,1L,1L,
             1L,1L,1L,1L,1L,1L,1L,1L,1L,1L,1L,1L,2L,1L,
             1L,1L,1L,1L,1L,1L,1L,1L,1L,1L,1L,1L,1L,1L,
             1L,1L,1L,1L,32L,32L,32L,1L,32L,1L,1L,1L,1L,1L,
             1L,1L,1L,1L,1L,1L,1L,1L,1L,1L,1L,1L,1L,1L,
             1L,1L,2L,2L,1L,1L,1L,1L,1L,1L,1L,1L,1L,1L,
             1L,1L,1L,1L,1L,1L,1L,1L,1L,1L,1L,1L,1L,1L,
             1L,1L,1L,1L,1L,1L,1L,1L,1L,1L,1L,1L,1L,1L,1L,
             1L,1L,1L,1L,1L,1L,1L,1L,51L,51L,11L,11L,0L,
             0L,0L,1L,1L,1L,1L,1L,1L,1L,1L,1L,1L,1L,1L,
             1L,1L,1L,1L,1L,1L,1L,1L,1L,1L,1L,1L,1L,1L,
             1L,1L,1L,1L,1L,1L,1L,1L,0L,1L,1L,1L,24L,1L,
             1L,1L,1L,1L,1L,1L,1L,1L,1L,1L,1L,1L,1L,1L,1L,
             1L,1L,1L,1L,1L,1L,1L,1L,1L,1L,1L,1L,1L,1L,
             1L,1L,1L,1L,1L,1L,1L,1L,1L,1L,1L,1L,1L,1L,
             1L,1L,1L,1L,1L,1L,1L,1L,1L,1L,1L,1L,1L,1L,
             1L,1L,1L,1L,1L,1L,1L,1L,1L,1L,1L,1L,1L,1L,1L,
             1L,1L,1L,1L,1L,1L),
      V3 = c(1L,2L,3L,4L,5L,6L,7L,8L,
             9L,10L,11L,12L,13L,14L,15L,16L,17L,18L,19L,
             20L,21L,22L,23L,24L,25L,26L,27L,28L,29L,30L,31L,
             32L,33L,34L,35L,36L,37L,38L,39L,40L,41L,42L,
             43L,44L,45L,46L,47L,48L,49L,50L,51L,52L,53L,54L,
             55L,56L,57L,58L,59L,60L,61L,62L,63L,64L,65L,
             66L,67L,68L,69L,70L,71L,72L,73L,74L,75L,76L,
             77L,78L,79L,80L,81L,82L,83L,84L,85L,86L,87L,88L,
             89L,90L,91L,92L,93L,94L,95L,96L,97L,98L,99L,
             100L,101L,102L,103L,104L,105L,106L,107L,108L,109L,
             110L,111L,112L,113L,114L,115L,116L,117L,118L,
             119L,120L,121L,122L,123L,124L,125L,126L,127L,128L,
             129L,130L,131L,132L,133L,134L,135L,136L,137L,
             138L,139L,140L,141L,142L,143L,144L,145L,146L,147L,
             148L,149L,150L,151L,152L,153L,154L,155L,156L,
             157L,158L,159L,160L,161L,162L,163L,164L,165L,166L,
             167L,168L,169L,170L,171L,172L,173L,174L,175L,
             177L,178L,179L,180L,181L,182L,183L,184L,185L,186L,
             187L,188L,189L,190L,191L,192L,193L,194L,195L,
             196L,197L,198L,199L,200L,201L,202L,203L,204L,205L,
             206L,207L,208L,209L,210L,211L,213L,214L,215L,
             216L,217L,218L,219L,220L,221L,222L,223L,224L,225L,
             227L,228L,229L,230L,231L,232L,233L,234L,235L,
             236L,237L,238L,239L,240L,241L,242L,243L,244L,245L,
             246L,247L,248L,249L,250L,251L,252L,253L,254L,
             255L,256L,257L,258L,259L,260L,261L,263L,264L,265L,
             266L,267L,268L,269L,270L,271L,272L,273L,274L,
             276L,277L,278L,279L,280L,282L,283L,284L,285L,286L,
             287L,288L,289L,290L,291L,292L,293L,294L,295L,
             296L,297L,298L,299L,300L,301L,302L,303L,304L,305L,
             307L,308L,309L,310L,311L,312L,313L,314L,315L,
             317L,318L,319L,320L,321L,322L,323L,324L,327L,328L,
             329L,330L,331L,332L,333L,334L,335L,336L,337L,
             339L,340L,341L,342L,343L,344L,348L,349L,351L,352L,
             353L,354L,355L,356L,357L,358L,359L,360L,361L,
             362L,363L,364L,365L,366L,367L,368L,369L,370L,371L,
             372L,373L,374L,375L,376L,377L,378L,379L,380L,
             381L,382L,383L,384L,385L,386L,387L,388L,389L,390L,
             391L,392L,393L,394L,396L,397L,398L,399L,400L,
             401L,402L,403L,404L,405L,406L,407L,408L,409L,482L,
             483L),
      V4 = c("iaitems","iaitems","iaitems",
             "iaitems","iaitems","iaitems","iaitems","iaitems",
             "iaitems","iaitems","iaitems","iaitems","iaitems",
             "iaitems","iaitems","iaitems","iaitems","iaitems",
             "iaitems","iaitems","iaitems","iaitems","iaitems",
             "iaitems","iaitems","iaitems","iaitems","iaitems",
             "iaitems","iaitems","iaitems","iaitems","iaitems","iaitems",
             "iaitems","iaitems","iaitems","iaitems","iaitems",
             "iaitems","iaitems","iaitems","iaitems","iaitems",
             "iaitems","iaitems","iaitems","iaitems","iaitems",
             "iaitems","iaitems","iaitems","iaitems","iaitems",
             "iaitems","iaitems","iaitems","iaitems","iaitems","iaitems",
             "iaitems","iaitems","iaitems","iaitems","iaitems",
             "iaitems","iaitems","iaitems","iaitems","iaitems",
             "iaitems","iaitems","iaitems","iaitems","iaitems",
             "iaitems","iaitems","iaitems","iaitems","iaitems",
             "iaitems","iaitems","iaitems","iaitems","iaitems",
             "iaitems","iaitems","iaitems","iaitems","iaitems","iaitems",
             "iaitems","iaitems","iaitems","iaitems","iaitems",
             "iaitems","iaitems","iaitems","iaitems","iaitems",
             "iaitems","iaitems","iaitems","iaitems","iaitems",
             "iaitems","iaitems","iaitems","iaitems","iaitems",
             "iaitems","iaitems","iaitems","iaitems","iaitems","iaitems",
             "iaitems","iaitems","iaitems","iaitems","iaitems",
             "iaitems","iaitems","iaitems","iaitems","iaitems",
             "iaitems","iaitems","iaitems","iaitems","iaitems",
             "iaitems","iaitems","iaitems","iaitems","iaitems",
             "iaitems","iaitems","iaitems","iaitems","iaitems",
             "iaitems","iaitems","iaitems","iaitems","iaitems","iaitems",
             "iaitems","iaitems","iaitems","iaitems","iaitems",
             "iaitems","iaitems","iaitems","iaitems","iaitems",
             "iaitems","iaitems","iaitems","iaitems","iaitems",
             "iaitems","iaitems","iaitems","iaitems","iaitems",
             "iaitems","iaitems","iaitems","iaitems","iaitems","iaitems",
             "iaitems","iaitems","iaitems","iaitems","iaitems",
             "iaitems","iaitems","iaitems","iaitems","iaitems",
             "iaitems","iaitems","iaitems","iaitems","iaitems",
             "iaitems","iaitems","iaitems","iaitems","iaitems",
             "iaitems","iaitems","iaitems","iaitems","iaitems",
             "iaitems","iaitems","iaitems","iaitems","iaitems","iaitems",
             "iaitems","iaitems","iaitems","iaitems","iaitems",
             "iaitems","iaitems","iaitems","iaitems","iaitems",
             "iaitems","iaitems","iaitems","iaitems","iaitems",
             "iaitems","iaitems","iaitems","iaitems","iaitems",
             "iaitems","iaitems","iaitems","iaitems","iaitems","iaitems",
             "iaitems","iaitems","iaitems","iaitems","iaitems",
             "iaitems","iaitems","iaitems","iaitems","iaitems",
             "iaitems","iaitems","iaitems","iaitems","iaitems",
             "iaitems","iaitems","iaitems","iaitems","iaitems",
             "iaitems","iaitems","iaitems","iaitems","iaitems",
             "iaitems","iaitems","iaitems","iaitems","iaitems","iaitems",
             "iaitems","iaitems","iaitems","iaitems","iaitems",
             "iaitems","iaitems","iaitems","iaitems","iaitems",
             "iaitems","iaitems","iaitems","iaitems","iaitems",
             "iaitems","iaitems","iaitems","iaitems","iaitems",
             "iaitems","iaitems","iaitems","iaitems","iaitems","iaitems",
             "iaitems","iaitems","iaitems","iaitems","iaitems",
             "iaitems","iaitems","iaitems","iaitems","iaitems",
             "iaitems","iaitems","iaitems","iaitems","iaitems",
             "iaitems","iaitems","iaitems","iaitems","iaitems",
             "iaitems","iaitems","iaitems","iaitems","iaitems",
             "iaitems","iaitems","iaitems","iaitems","iaitems","iaitems",
             "iaitems","iaitems","iaitems","iaitems","iaitems",
             "iaitems","iaitems","iaitems","iaitems","iaitems",
             "iaitems","iaitems","iaitems","iaitems","iaitems",
             "iaitems","iaitems","iaitems","iaitems","iaitems",
             "iaitems","iaitems","iaitems","iaitems","iaitems","iaitems",
             "iaitems","iaitems","iaitems","iaitems","iaitems",
             "iaitems","iaitems","iaitems","iaitems","iaitems",
             "iaitems","iaitems","iaitems","iaitems","iaitems",
             "iaitems","iaitems","iaitems","iaitems","iaitems",
             "iaitems","iaitems","iaitems","iaitems","iaitems",
             "iaitems","iaitems","iaitems","iaitems","iaitems","iaitems",
             "iaitems","iaitems","iaitems","iaitems","iaitems",
             "iaitems","iaitems","iaitems","iaitems","iaitems",
             "iaitems","iaitems","iaitems","iaitems","iaitems",
             "iaitems","iaitems","iaitems","iaitems"),
      V5 = c("Cash and Short-Term Investments","Receivables/Total","Inventories - Total",
             "Current Assets - Total","Current Liabilities - Total",
             "Assets - Total",
             "\"Property, Plant and Equipment - Total (Gross)\"","\"Property, Plant and Equipment - Total (Net)\"",
             "Long-Term Debt - Total",
             "Preferred Stock/Liquidating Value","Common Equity/Tangible","Sales/Turnover Net)",
             "Operating Income Before Depreciation",
             "Depreciation and Amortization","Interest and Related Expense - Total",
             "Income Taxes - Total","Special Items",
             "Income Before Extraordinary Items","Dividends - Preferred/Preference",
             "Income Before Extraordinary Items/Adjusted for Common Stock Equivalents","Dividends Common/Ordinary",
             "Price High - Annual","Price Low - Annual","Price Close - Annual",
             "Common Shares Outstanding","Dividends per Share/Ex-Date",
             "Adjustment Factor (Company) - Cumulative by Ex-Date",
             "Common Shares Traded - Annual","Employees",
             "\"Capital Expend Property, Plant and Equipment Schd V\"",
             "Investment and Advances - Equity","Investment and Advances/Other",
             "Intangible Assets - Total",
             "Debt in Current Liabilities - Total","Deferred Taxes and Investment Tax Credit",
             "Retained Earnings","Invested Capital - Total",
             "Minority Interest (Balance Sheet)",
             "Convertible Debt and Preferred Stock","Common Shares Reserved for Conversion/Total",
             "Cost of Goods Sold","Staff Expense - Total",
             "Pension and Retirement Expense",
             "Long-Term Debt Due in One Year","Advertising Expense",
             "Research and Development Expense","Rental Expense",
             "Extraordinary Items and Discontinued Operations","Minority Interest (Income Account)",
             "Income Taxes - Deferred",
             "Investment Tax Credit (Income Account)","Tax Loss Carry Forward",
             "Earnings Per Share (Basic)/Including Extraordinary Items",
             "Common Shares Used to Calculate Earnings Per Share/Basic",
             "Equity in Earnings - Unconsolidated Subsidiaries",
             "Preferred Stock/Redemption Value",
             "Earnings Per Share (Diluted)/Excluding Extraordinary Items",
             "Earnings Per Share (Basic)/Excluding Extraordinary Items","Inventory Valuation Method",
             "Common/Ordinary Equity - Total",
             "Nonoperating Income (Expense)","Interest and Related Income - Total",
             "Income Taxes/Federal","Income Taxes - Foreign",
             "Amortization of Intangibles","Discontinued Operations",
             "Receivables - Estimated Doubtful","Current Assets/Other/Total",
             "Assets - Other","Accounts Payable - Trade",
             "Income Taxes Payable","Current Liabilities/Other/Total",
             "\"Property, Plant, and Equipment/Construction in Progress (Net)\"",
             "Deferred Taxes Balance Sheet)","Liabilities - Other - Total",
             "Inventories/Raw Materials",
             "Inventories/Work In Process","Inventories /Finished Goods","Debt - Convertible",
             "Debt-Subordinated","Debt/Notes","Debt/Debentures",
             "Other Long-term Debt",
             "Debt/Capitalized Lease Obligations","Common/Ordinary Stock (Capital)",
             "Treasury Stock Book Value/Memo Entry",
             "Treasury Stock/Number of Common Shares","Treasury Stock - Total (All Capital)",
             "Pension Costs/Unfunded Vested Benefits",
             "Pension Costs/Unfunded Past or Prior Service","Debt/Due in 2nd Year",
             "Debt/Due in 3rd Year","Debt/Due in 4th Year",
             "Debt/Due in 5th Year","Rental Commitments/Minimum/5 Year Total",
             "Rental Commitments/Minimum/1st Year",
             "Retained Earnings/Unrestricted","Order Backlog","Retained Earnings/Restatement",
             "Common/Ordinary Shareholders",
             "Interest Expense - Long-Term Debt","Excise Taxes",
             "Depreciation Expense (Schedule VI)","Average Short-Term Borrowings",
             "Average Short-Term Borrowings Rate","Equity in Net Loss/Earnings",
             "Sale of Property","Sale of Common and Preferred Stock",
             "Sale of Investments","Funds From Operations/Total",
             "Long-Term Debt/Issuance","Sources of Funds/Total",
             "Increase in Investments","Long-Term Debt/Reduction",
             "Purchase of Common and Preferred Stock","Uses of Funds/Total",
             "Sales/Turnover (Net)","Income Before Extraordinary Items",
             "Earnings Per Share (Basic)/Excluding Extraordinary Items","Assets - Total","Working Capital (Balance Sheet)",
             "Pretax Income",
             "Income Before Extraordinary Items (Cash Flow)",
             "Extraordinary Items and Discontinued Operations (Cash Flow)","Depreciation and Amortization (Cash Flow)",
             "Deferred Taxes (Cash Flow)",
             "Cash Dividends (Cash Flow)","Capital Expenditures","Acquisitions",
             "Preferred/Preference Stock (Capital) - Total","Cost of Goods Sold",
             "\"Selling, General and Administrative Expense\"",
             "Depreciation and Amortization",
             "Interest and Related Expense - Total","Income Taxes - Total",
             "Extraordinary Items and Discontinued Operations",
             "Earnings Per Share (Basic)/Including Extraordinary Items",
             "Common Shares Used to Calculate Earnings Per Share/Basic",
             "Earnings Per Share (Diluted)/Excluding Extraordinary Items",
             "Earnings Per Share (Diluted)/Including Extraordinary Items",
             "\"Property, Plant and Equipment - Total (Net)\"",
             "Long-Term Debt - Total","Retained Earnings/Unadjusted",
             "Stockholders' Equity - Total","Capital Expenditures","Employees",
             "Interest Capitalized","Long-Term Debt/Tied to Prime",
             "Auditor Opinion","Foreign Exchange Income (Loss)",
             "Receivables - Trade","Deferred Charges","Accrued Expenses",
             "Debt /Subordinated Convertible",
             "\"Property, Plant, and Equipment/Buildings (Net) \"",
             "\"Property, Plant, and Equipment/Machinery and Equipment (Net)\"",
             "\"Property, Plant, and Equipment/Natural Resources (Net)\"",
             "\"Property, Plant, and Equipment/Land and Improvements (Net)\"",
             "\"Property, Plant, and Equipment/Leases (Net)\"",
             "Prepaid Expenses","Income Tax Refund","Cash","Rental Income",
             "Rental Commitments/Minimum/2nd Year",
             "Rental Commitments/Minimum/3rd Year","Rental Commitments/Minimum/4th Year",
             "Rental Commitments/Minimum/5th Year",
             "Compensating Balance",
             "Earnings Per Share (Diluted)/Including Extraordinary Items","Pretax Income",
             "Common Shares Used to Calc Earnings Per Share/Fully Diluted","Net Income (Loss)",
             "Income Taxes/State","Depletion Expense (Schedule VI)",
             "Preferred/Preference Stock - Redeemable",
             "Net Income (Loss)","Operating Income After Depreciation",
             "Working Capital (Balance Sheet)","Working Capital Change/Total",
             "Liabilities - Total",
             "\"Property, Plant and Equipment/Beginning Balance (Schedule V)\"",
             "Accounting Changes/Cumulative Effect",
             "\"Property, Plant and Equipment/Retirements (Schedule V)\"",
             "\"Property, Plant, and Equipment/Other Changes (Schedule V)\"","Inventories /Other",
             "\"Property, Plant, and Equipment/Ending Balance (Schedule V)\"","Debt /Senior Convertible",
             "\"Selling, General and Administrative Expense\"",
             "Nonoperating Income (Expense)/Other","Common Stock Equivalents - Dollar Savings",
             "Extraordinary Items","Short-Term Investments - Total",
             "Receivables - Current - Other","Current Assets/Other/Sundry",
             "\"Depreciation, Depletion and Amortization (Accumulated)\"","Price High - Annual","Price Low - Annual",
             "Price Close - Annual",
             "Common Shares Reserved for Conversion/Convertible Debt","Dividends per Share/Pay Date",
             "Adjustment Factor (Company) - Cumulative byPay-Date",
             "Common Shares Reserved for Conversion/Preferred Stock",
             "Goodwill","Assets - Other - Sundry",
             "Notes Payable/Short-Term Borrowings","Current Liabilities/Other/Sundry",
             "Investment Tax Credit (Balance Sheet)",
             "Preferred/Preference Stock - Nonredeemable",
             "Capital Surplus/Share Premium Reserve","Income Taxes - Other",
             "\"Sale of Property, Plant and Equipment and Investments/Gain (Loss)\"",
             "Preferred Stock/Convertible",
             "Common Shares Reserved for Conversion/Stock Options","Stockholders' Equity - Total",
             "Funds from Operations/Other","Sources of Funds/Other",
             "Uses of Funds/Other",
             "Depreciation (Accumulated)/Beginning Balance (Schedule VI)",
             "Depreciation (Accumulated)/Retirements (Schedule VI)",
             "Depreciation (Accumulated)/Other Changes (Schedule VI)",
             "Depreciation (Accumulated)/Ending Balance (Schedule VI)","Nonoperating Income (Expense)",
             "Minority Interest (Income Account)",
             "Treasury Stock - Preferrred","Currency Translation Rate",
             "Common Shares Reserved for Conversion/Warrants and Other",
             "Retained Earnings/Cumulative Translation Adjustment",
             "Retained Earnings/Other Adjustments","Common Stock-Carrying Value",
             "Earnings Per Share from Operations","ADR Ratio",
             "Common Equity/Liquidation Value",
             "Working Capital Change/Other/Increase/(Decrease)",
             "Income Before Extraordinary Items/Available for Common","Marketable Securities Adjustment",
             "Net Income Effect Capitalized Interest",
             "LIFO Reserve","Debt /Mortgages & Other Secured",
             "Preferred Dividends in Arrears","Pension Benefits/Present Value of Vested",
             "Pension Benefits/Present Value of Nonvested",
             "Pension Benefits/Net Assets",
             "Pension Benefits Discount Rate/Assumed Rate of Return","Pension Benefit/Information Date",
             "Acquisitions /Income Contribution",
             "Acquisitions /Sales Contribution",
             "\"Property, Plant, and Equipment/Other (Net)\"",
             "Depreciation (Accumulated)/Land and Improvements","Depreciation (Accumulated)/Natural Resources",
             "Depreciation (Accumulated)/Buildings",
             "Depreciation (Accumulated)/Machinery and Equipment",
             "Depreciation (Accumulated)/Leases",
             "Depreciation (Accumulated)/Construction in Progress","Depreciation (Accumulated)/Other",
             "Net Income Adjusted for Common/Ordinary Stock (Capital) Equivalents","Retained Earnings/Unadjusted",
             "\"Property, Plant, and Equipment/Land and Improvements at Cost\"",
             "\"Property, Plant, and Equipment/Natural Resources at Cost\"",
             "\"Property, Plant, and Equipment/Buildings at Cost\"",
             "\"Property, Plant, and Equipment/Machinery and Equipment at Cost\"",
             "\"Property, Plant, and Equipment/Leases at Cost\"",
             "\"Property, Plant, and Equipment/Construction in Progress at Cost\"",
             "\"Property, Plant, and Equipment/Other at Cost\"",
             "Debt /Unamortized Debt Discount and Other","Deferred Taxes-Federal","Deferred Taxes-Foreign",
             "Deferred Taxes-State","Pretax Income/Domestic",
             "Pretax Income/Foreign",
             "Cash and Cash Equivalents/Increase/(Decrease)","S&P Major Index Code/Historical",
             "S&P Industry Index Code/Historical","Fortune Industry Code",
             "Fortune Rank","S&P Domestic Long Term Issuer Credit Rating",
             "S&P Quality Rank",
             "S&P Domestic Short Term Issuer Credit Rating","Pension /Vested Benefit Obligation",
             "Pension /Accumulated Benefit Obligation",
             "Pension /Projected Benefit Obligation","Pension Plan Assets",
             "Pension /Unrecognized Prior Service Cost","Pension /Other Adjustments",
             "Pension /Prepaid/Accrued Cost",
             "Pension /Vested Benefit Obligation (Underfunded)",
             "Periodic Postretirement Benefit Cost (Net)",
             "Pension /Accumulated Benefit Obligation (Underfunded)",
             "Pension /Projected Benefit Obligation (Underfunded)","Periodic Pension Cost (Net)",
             "Pension Plan Assets (Underfunded)",
             "Pension /Unrecognized Prior Service Cost (Underfunded)",
             "Pension /Additional Minimum Liability (Underfunded)",
             "Pension /Other Adjustments (Underfunded)","Pension /Prepaid/Accrued Cost (Underfunded)",
             "Current Debt/Changes",
             "Accounts Receivable/Decrease (Increase)","Inventory /Decrease (Increase)",
             "Accounts Payable and Accrued Liabilities/Increase/(Decrease)",
             "Income Taxes/Accrued/Increase/(Decrease)",
             "Assets and Liabilities/Other/Net Change",
             "Operating Activities/Net Cash Flow","Short-Term Investments/Change",
             "Investing Activities/Other","Investing Activities/Net Cash Flow",
             "Financing Activities/Other",
             "Financing Activities/Net Cash Flow","Exchange Rate Effect","Interest Paid/Net",
             "Income Taxes Paid","Cash Flow Format","Dilution Adjustment",
             "S&P Subordinated Debt Rating",
             "Interest Income/Total (Financial Services)",
             "Dilution Available/Excluding Extraordinary Items",
             "Earnings Per Share/Diluted/from Operations","Standard Industrial Classification - Historical",
             "Contingent Liabilities - Guarantees",
             "Debt /Finance Subsidiary","Debt /Consolidated Subsidiary",
             "Postretirement Benefit Asset","Pension Plans/Service Cost",
             "Pension Plans/Interest Cost",
             "Pension Plans/Return on Plan Assets (Expected)",
             "Pension Plans/Other Periodic Cost Components (Net)","Pension Plans/Rate of Compensation Increase",
             "Pension Plans/Anticipated Long-Term Rate of Return on Plan Assets","Risk-Adjusted Capital Ratio - Tier 1",
             "Interest Expense/Total (Financial Services)",
             "Net Interest Income (Tax Equivalent)","Nonperforming Assets - Total",
             "Provision for Loan/Asset Losses",
             "Reserve for Loan/Asset Losses","Net Interest Margin",
             "Risk-Adjusted Capital Ratio/Total","Net Charge-Offs",
             "Current Assets of Discontinued Operations","Other Intangibles",
             "Long-term Assets of Discontinued Operations",
             "Other Current Assets Excl Discontinued Operations",
             "Other Assets excluding Discontinued Operations","Deferred Revenue/Current",
             "Accumulated Other Comprehensive Income (Loss)",
             "Deferred Compensation","Other Stockholders  Equity Adjustments",
             "Acquisition/Merger Pretax","Acquisition/Merger After-tax",
             "Acquisition/Merger Basic EPS Effect",
             "Acquisition/Merger Diluted EPS Effect","Gain/Loss Pretax",
             "Gain/Loss After-tax","Gain/Loss Basic EPS Effect",
             "Gain/Loss Diluted EPS Effect","Impairments of Goodwill Pretax",
             "Impairments of Goodwill After-tax",
             "Impairments of Goodwill Basic EPS Effect",
             "Impairments of Goodwill Diluted EPS Effect","Settlement (Litigation/Insurance) Pretax",
             "Settlement (Litigation/Insurance) After-tax",
             "Settlement (Litigation/Insurance) Basic EPS Effect",
             "Settlement (Litigation/Insurance) Diluted EPS Effect",
             "Restructuring Costs Pretax","Restructuring Costs After-tax",
             "Restructuring Costs Basic EPS Effect",
             "Restructuring Costs Diluted EPS Effect","Writedowns Pretax","Writedowns After-tax",
             "Writedowns Basic EPS Effect","Writedowns Diluted EPS Effect",
             "Other Special Items Pretax",
             "Other Special Items After-tax","Other Special Items Basic EPS Effect",
             "Other Special Items Diluted EPS Effect","In Process R&D Expense",
             "Thereafter Portion of Leases",
             "Accumulated Depreciation of RE Property","Total RE Property",
             "Gain/Loss on Sale of Property","Depr/Amort of Property",
             "Goodwill Amortization","Common Shares Issued",
             "Deferred Revenue/Long-term","Stock Compensation Expense",
             "Implied Option Expense",
             "Excess Tax Benefit of Stock Options - Cash Flow Financing","In Process R&D Expense Basic EPS Effect",
             "In Process R&D Expense Diluted EPS Effect",
             "Nonrecurring Income Taxes After-tax",
             "Nonrecurring Income Tax Basic EPS Effect","Nonrecurring Income Tax Diluted EPS Effect",
             "Extinguishment of Debt Pretax",
             "Extinguishment of Debt After-tax","Extinguishment of Debt Basic EPS Effect",
             "Extinguishment of Debt Diluted EPS Effect",
             "Implied Option EPS Basic","Implied Option EPS Diluted")
    )
names(df) <- c("New CCM Item Name", "Keyset","Legacy CST Item Number","Legacy CST Item Name","Description")
write.csv(df,"get_data_dict.csv",row.names = FALSE)
